name = "TotalUnimodularity"
uuid = "dae517f8-2e2b-4a6d-bb8c-ca4a989a6097"
version = "0.1.0"
authors = ["Michael McVeagh <mcveagh@gmail.com>"]

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
Combinatorics = "1.1.0"
LinearAlgebra = "1.12.0"
julia = "1.6"
